//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fantania.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fantania.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string ButtonTextAdd {
            get {
                return ResourceManager.GetString("ButtonTextAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Background.
        /// </summary>
        public static string ButtonTextAddBackground {
            get {
                return ResourceManager.GetString("ButtonTextAddBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Foreground.
        /// </summary>
        public static string ButtonTextAddForeground {
            get {
                return ResourceManager.GetString("ButtonTextAddForeground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string ButtonTextClear {
            get {
                return ResourceManager.GetString("ButtonTextClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Level.
        /// </summary>
        public static string ButtonTextCreateLevel {
            get {
                return ResourceManager.GetString("ButtonTextCreateLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer Visibility.
        /// </summary>
        public static string ButtonTextLayerVisibility {
            get {
                return ResourceManager.GetString("ButtonTextLayerVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Editor.
        /// </summary>
        public static string ButtonTextOpenEditor {
            get {
                return ResourceManager.GetString("ButtonTextOpenEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        public static string ButtonTextRandom {
            get {
                return ResourceManager.GetString("ButtonTextRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stylegrounds.
        /// </summary>
        public static string ButtonTextStylegrounds {
            get {
                return ResourceManager.GetString("ButtonTextStylegrounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level name already exists..
        /// </summary>
        public static string ErrorDuplicateLevelName {
            get {
                return ResourceManager.GetString("ErrorDuplicateLevelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level name can&apos;t be empty..
        /// </summary>
        public static string ErrorEmptyLevelName {
            get {
                return ResourceManager.GetString("ErrorEmptyLevelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid level name, should be combination of letters, numbers and underlines..
        /// </summary>
        public static string ErrorInvalidLevelName {
            get {
                return ResourceManager.GetString("ErrorInvalidLevelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing: &apos;{0}&apos;..
        /// </summary>
        public static string LogExecutingSql {
            get {
                return ResourceManager.GetString("LogExecutingSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Panel.
        /// </summary>
        public static string LogPanelHeader {
            get {
                return ResourceManager.GetString("LogPanelHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace: &apos;{0}&apos; was initialized..
        /// </summary>
        public static string LogWorkspaceInitialized {
            get {
                return ResourceManager.GetString("LogWorkspaceInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace: &apos;{0}&apos; was opened..
        /// </summary>
        public static string LogWorkspaceOpened {
            get {
                return ResourceManager.GetString("LogWorkspaceOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace: &apos;{0}&apos; was saved..
        /// </summary>
        public static string LogWorkspaceSaved {
            get {
                return ResourceManager.GetString("LogWorkspaceSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string MainMenuDatabase {
            get {
                return ResourceManager.GetString("MainMenuDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string MainMenuDebug {
            get {
                return ResourceManager.GetString("MainMenuDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual.
        /// </summary>
        public static string MainMenuDebugVisual {
            get {
                return ResourceManager.GetString("MainMenuDebugVisual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BVH Visualizer.
        /// </summary>
        public static string MainMenuDebugVisualBVH {
            get {
                return ResourceManager.GetString("MainMenuDebugVisualBVH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string MainMenuEdit {
            get {
                return ResourceManager.GetString("MainMenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string MainMenuEditCopy {
            get {
                return ResourceManager.GetString("MainMenuEditCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string MainMenuEditCut {
            get {
                return ResourceManager.GetString("MainMenuEditCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string MainMenuEditDuplicate {
            get {
                return ResourceManager.GetString("MainMenuEditDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string MainMenuEditPaste {
            get {
                return ResourceManager.GetString("MainMenuEditPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string MainMenuEditRedo {
            get {
                return ResourceManager.GetString("MainMenuEditRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string MainMenuEditUndo {
            get {
                return ResourceManager.GetString("MainMenuEditUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MainMenuFile {
            get {
                return ResourceManager.GetString("MainMenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Workspace.
        /// </summary>
        public static string MainMenuFileCloseWorkspace {
            get {
                return ResourceManager.GetString("MainMenuFileCloseWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MainMenuFileExit {
            get {
                return ResourceManager.GetString("MainMenuFileExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Workspace.
        /// </summary>
        public static string MainMenuFileNewWorkspace {
            get {
                return ResourceManager.GetString("MainMenuFileNewWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Workspace.
        /// </summary>
        public static string MainMenuFileOpenWorkspace {
            get {
                return ResourceManager.GetString("MainMenuFileOpenWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        public static string MainMenuFilePreferences {
            get {
                return ResourceManager.GetString("MainMenuFilePreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Workspace.
        /// </summary>
        public static string MainMenuFileSaveWorkspace {
            get {
                return ResourceManager.GetString("MainMenuFileSaveWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string MainMenuView {
            get {
                return ResourceManager.GetString("MainMenuView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fantania.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageBoxCaptionError {
            get {
                return ResourceManager.GetString("MessageBoxCaptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string MessageBoxCaptionMessage {
            get {
                return ResourceManager.GetString("MessageBoxCaptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string MessageBoxCaptionWarning {
            get {
                return ResourceManager.GetString("MessageBoxCaptionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workspace does already exist.If you continue creating the workspace, all data will be cleared, are you sure to continue with it?.
        /// </summary>
        public static string MessageConfirmReinitializeWorkspace {
            get {
                return ResourceManager.GetString("MessageConfirmReinitializeWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to remove &apos;{0}&apos;?.
        /// </summary>
        public static string MessageConfirmRemoveObject {
            get {
                return ResourceManager.GetString("MessageConfirmRemoveObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are gonna to remove &apos;{0}&apos;, continue?.
        /// </summary>
        public static string MessageDeleteStyleground {
            get {
                return ResourceManager.GetString("MessageDeleteStyleground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid Fantania workspace. Error: {1}.
        /// </summary>
        public static string MessageInvalidWorkspace {
            get {
                return ResourceManager.GetString("MessageInvalidWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Workspace.
        /// </summary>
        public static string OverviewPanelWorkspaceHeader {
            get {
                return ResourceManager.GetString("OverviewPanelWorkspaceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoration.
        /// </summary>
        public static string PlacementDecoration {
            get {
                return ResourceManager.GetString("PlacementDecoration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawables Stylegrounds.
        /// </summary>
        public static string PlacementDrawablesStylegrounds {
            get {
                return ResourceManager.GetString("PlacementDrawablesStylegrounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gradient Stylegrounds.
        /// </summary>
        public static string PlacementGradientStylegrounds {
            get {
                return ResourceManager.GetString("PlacementGradientStylegrounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placements.
        /// </summary>
        public static string PlacementPanelHeader {
            get {
                return ResourceManager.GetString("PlacementPanelHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stylegrounds.
        /// </summary>
        public static string PlacementStylegrounds {
            get {
                return ResourceManager.GetString("PlacementStylegrounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlit Curved Sprite.
        /// </summary>
        public static string PlacementUnlitCurvedSprite {
            get {
                return ResourceManager.GetString("PlacementUnlitCurvedSprite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlit Noise Curved Sprite.
        /// </summary>
        public static string PlacementUnlitNoiseSprite {
            get {
                return ResourceManager.GetString("PlacementUnlitNoiseSprite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlit Sprite.
        /// </summary>
        public static string PlacementUnlitSprite {
            get {
                return ResourceManager.GetString("PlacementUnlitSprite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string PreviewPanelHeader {
            get {
                return ResourceManager.GetString("PreviewPanelHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Name.
        /// </summary>
        public static string PropertiesViewHeaderName {
            get {
                return ResourceManager.GetString("PropertiesViewHeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Value.
        /// </summary>
        public static string PropertiesViewHeaderValue {
            get {
                return ResourceManager.GetString("PropertiesViewHeaderValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties Panel.
        /// </summary>
        public static string PropertyPanelHeader {
            get {
                return ResourceManager.GetString("PropertyPanelHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stylegrounds.
        /// </summary>
        public static string StylegroundsPanelHeader {
            get {
                return ResourceManager.GetString("StylegroundsPanelHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Level.
        /// </summary>
        public static string TitleLevelCreate {
            get {
                return ResourceManager.GetString("TitleLevelCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styleground Editor.
        /// </summary>
        public static string TitleStylegroundEditor {
            get {
                return ResourceManager.GetString("TitleStylegroundEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anchor position affects the body visual of objects, X, Y component must be in the range of [0.0, 1.0]..
        /// </summary>
        public static string TooltipAnchor {
            get {
                return ResourceManager.GetString("TooltipAnchor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can comment something crucial here..
        /// </summary>
        public static string TooltipComment {
            get {
                return ResourceManager.GetString("TooltipComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha Cutoff, the pixels below the cutoff will be discard..
        /// </summary>
        public static string TooltipCutoff {
            get {
                return ResourceManager.GetString("TooltipCutoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrollable drawables styleground..
        /// </summary>
        public static string TooltipDrawablesStylegrounds {
            get {
                return ResourceManager.GetString("TooltipDrawablesStylegrounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom edge settings..
        /// </summary>
        public static string TooltipEdgeBottom {
            get {
                return ResourceManager.GetString("TooltipEdgeBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left edge settings..
        /// </summary>
        public static string TooltipEdgeLeft {
            get {
                return ResourceManager.GetString("TooltipEdgeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right edge settings..
        /// </summary>
        public static string TooltipEdgeRight {
            get {
                return ResourceManager.GetString("TooltipEdgeRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top edge settings..
        /// </summary>
        public static string TooltipEdgeTop {
            get {
                return ResourceManager.GetString("TooltipEdgeTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gradient texture..
        /// </summary>
        public static string TooltipGradientSprite {
            get {
                return ResourceManager.GetString("TooltipGradientSprite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple gradient stylegrounds..
        /// </summary>
        public static string TooltipGradientStylegrounds {
            get {
                return ResourceManager.GetString("TooltipGradientStylegrounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Render layer in the level..
        /// </summary>
        public static string TooltipLayer {
            get {
                return ResourceManager.GetString("TooltipLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main texture of the object..
        /// </summary>
        public static string TooltipMainTexture {
            get {
                return ResourceManager.GetString("TooltipMainTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines how the object is rendered..
        /// </summary>
        public static string TooltipMaterial {
            get {
                return ResourceManager.GetString("TooltipMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the object, you&apos;d better make it more recognizable..
        /// </summary>
        public static string TooltipName {
            get {
                return ResourceManager.GetString("TooltipName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noise texture..
        /// </summary>
        public static string TooltipNoise {
            get {
                return ResourceManager.GetString("TooltipNoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outline Color..
        /// </summary>
        public static string TooltipOutlineColor {
            get {
                return ResourceManager.GetString("TooltipOutlineColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outline Size..
        /// </summary>
        public static string TooltipOutlineSize {
            get {
                return ResourceManager.GetString("TooltipOutlineSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlit Static Sprite..
        /// </summary>
        public static string TooltipPlacementUnlitSprite {
            get {
                return ResourceManager.GetString("TooltipPlacementUnlitSprite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World position of the object..
        /// </summary>
        public static string TooltipPosition {
            get {
                return ResourceManager.GetString("TooltipPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative depth in the current layer, in [0, 999]..
        /// </summary>
        public static string TooltipRelativeDepth {
            get {
                return ResourceManager.GetString("TooltipRelativeDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local rotation of the object..
        /// </summary>
        public static string TooltipRotation {
            get {
                return ResourceManager.GetString("TooltipRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local scaling of the object..
        /// </summary>
        public static string TooltipScale {
            get {
                return ResourceManager.GetString("TooltipScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movement ratio at x-axis with camera moving..
        /// </summary>
        public static string TooltipScrollX {
            get {
                return ResourceManager.GetString("TooltipScrollX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movement ratio at y-axis with camera moving..
        /// </summary>
        public static string TooltipScrollY {
            get {
                return ResourceManager.GetString("TooltipScrollY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines what mesh the object uses..
        /// </summary>
        public static string TooltipShape {
            get {
                return ResourceManager.GetString("TooltipShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self movement speed at x-axis..
        /// </summary>
        public static string TooltipSpeedX {
            get {
                return ResourceManager.GetString("TooltipSpeedX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self movement speed at y-axis..
        /// </summary>
        public static string TooltipSpeedY {
            get {
                return ResourceManager.GetString("TooltipSpeedY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gradient style..
        /// </summary>
        public static string TooltipStylegroundGradient {
            get {
                return ResourceManager.GetString("TooltipStylegroundGradient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the styleground..
        /// </summary>
        public static string TooltipStylegroundName {
            get {
                return ResourceManager.GetString("TooltipStylegroundName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiling coordinates(x * u + z, y * v + w)..
        /// </summary>
        public static string TooltipTiling {
            get {
                return ResourceManager.GetString("TooltipTiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edge-curved sprite..
        /// </summary>
        public static string TooltipUnlitCurvedSprite {
            get {
                return ResourceManager.GetString("TooltipUnlitCurvedSprite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noised edge-curved sprite..
        /// </summary>
        public static string TooltipUnlitNoiseSprite {
            get {
                return ResourceManager.GetString("TooltipUnlitNoiseSprite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique Identifier of the object..
        /// </summary>
        public static string TooltipUUID {
            get {
                return ResourceManager.GetString("TooltipUUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex color of the object..
        /// </summary>
        public static string TooltipVertexColor {
            get {
                return ResourceManager.GetString("TooltipVertexColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backgrounds.
        /// </summary>
        public static string TreeViewHeaderBackgrounds {
            get {
                return ResourceManager.GetString("TreeViewHeaderBackgrounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foregrounds.
        /// </summary>
        public static string TreeViewHeaderForegrounds {
            get {
                return ResourceManager.GetString("TreeViewHeaderForegrounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format error, must be a number..
        /// </summary>
        public static string ValidationErrorDecimalFormat {
            get {
                return ResourceManager.GetString("ValidationErrorDecimalFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number should be in the range of [{0}, {1}]..
        /// </summary>
        public static string ValidationErrorDecimalRange {
            get {
                return ResourceManager.GetString("ValidationErrorDecimalRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name does already exist in the same group..
        /// </summary>
        public static string ValidationErrorDuplicatedName {
            get {
                return ResourceManager.GetString("ValidationErrorDuplicatedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name must be non-empty..
        /// </summary>
        public static string ValidationErrorEmptyName {
            get {
                return ResourceManager.GetString("ValidationErrorEmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format error, must be an integer..
        /// </summary>
        public static string ValidationErrorIntegerFormat {
            get {
                return ResourceManager.GetString("ValidationErrorIntegerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The integer should be in the range of [{0}, {1}]..
        /// </summary>
        public static string ValidationErrorIntegerRange {
            get {
                return ResourceManager.GetString("ValidationErrorIntegerRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error. Info: {0}..
        /// </summary>
        public static string ValidationErrorUnknown {
            get {
                return ResourceManager.GetString("ValidationErrorUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your workspace is modified, do you want to save the work?.
        /// </summary>
        public static string WarningConfirmSavingOnExit {
            get {
                return ResourceManager.GetString("WarningConfirmSavingOnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete level &apos;{0}&apos;? All data will be removed permanently and cannot recover!.
        /// </summary>
        public static string WarningDeleteLevel {
            get {
                return ResourceManager.GetString("WarningDeleteLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combination of letters, numbers and underlines..
        /// </summary>
        public static string WaterMarkNameConvention {
            get {
                return ResourceManager.GetString("WaterMarkNameConvention", resourceCulture);
            }
        }
    }
}
