//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fantania.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fantania.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清除.
        /// </summary>
        public static string BT_ClearLog {
            get {
                return ResourceManager.GetString("BT_ClearLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;不是一个有效的工作区，或者由于某些原因损坏了。.
        /// </summary>
        public static string ERR_Invalid_Workspace {
            get {
                return ResourceManager.GetString("ERR_Invalid_Workspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;不存在。.
        /// </summary>
        public static string ERR_NonExist_Workspace {
            get {
                return ResourceManager.GetString("ERR_NonExist_Workspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日志.
        /// </summary>
        public static string H_Log {
            get {
                return ResourceManager.GetString("H_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 实体.
        /// </summary>
        public static string H_Placements {
            get {
                return ResourceManager.GetString("H_Placements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 属性.
        /// </summary>
        public static string H_Properties {
            get {
                return ResourceManager.GetString("H_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑.
        /// </summary>
        public static string MI_Edit {
            get {
                return ResourceManager.GetString("MI_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 复制.
        /// </summary>
        public static string MI_Edit_Copy {
            get {
                return ResourceManager.GetString("MI_Edit_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 剪切.
        /// </summary>
        public static string MI_Edit_Cut {
            get {
                return ResourceManager.GetString("MI_Edit_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 粘贴.
        /// </summary>
        public static string MI_Edit_Paste {
            get {
                return ResourceManager.GetString("MI_Edit_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重做.
        /// </summary>
        public static string MI_Edit_Redo {
            get {
                return ResourceManager.GetString("MI_Edit_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 撤销.
        /// </summary>
        public static string MI_Edit_Undo {
            get {
                return ResourceManager.GetString("MI_Edit_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件.
        /// </summary>
        public static string MI_File {
            get {
                return ResourceManager.GetString("MI_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭工作区.
        /// </summary>
        public static string MI_File_CloseWorkspace {
            get {
                return ResourceManager.GetString("MI_File_CloseWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出.
        /// </summary>
        public static string MI_File_Exit {
            get {
                return ResourceManager.GetString("MI_File_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新建工作区.
        /// </summary>
        public static string MI_File_NewWorkspace {
            get {
                return ResourceManager.GetString("MI_File_NewWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开最近....
        /// </summary>
        public static string MI_File_OpenRecent {
            get {
                return ResourceManager.GetString("MI_File_OpenRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开工作区.
        /// </summary>
        public static string MI_File_OpenWorkspace {
            get {
                return ResourceManager.GetString("MI_File_OpenWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存工作区.
        /// </summary>
        public static string MI_File_SaveWorkspace {
            get {
                return ResourceManager.GetString("MI_File_SaveWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工作区&apos;{0}&apos;已经存在，你确定要继续吗？所有旧数据都会被清除。.
        /// </summary>
        public static string WARN_Replace_Exist_Workspace {
            get {
                return ResourceManager.GetString("WARN_Replace_Exist_Workspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入过滤文本....
        /// </summary>
        public static string WM_Filter {
            get {
                return ResourceManager.GetString("WM_Filter", resourceCulture);
            }
        }
    }
}
