//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fantania.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fantania.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清除.
        /// </summary>
        public static string BT_ClearLog {
            get {
                return ResourceManager.GetString("BT_ClearLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 拷贝.
        /// </summary>
        public static string BT_CopyLog {
            get {
                return ResourceManager.GetString("BT_CopyLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建一个关卡.
        /// </summary>
        public static string BT_CreateLevel {
            get {
                return ResourceManager.GetString("BT_CreateLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前关卡: {0}.
        /// </summary>
        public static string BT_CurrentLevel {
            get {
                return ResourceManager.GetString("BT_CurrentLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 层级管理.
        /// </summary>
        public static string BT_LayerManage {
            get {
                return ResourceManager.GetString("BT_LayerManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关卡设置.
        /// </summary>
        public static string BT_LevelMetadata {
            get {
                return ResourceManager.GetString("BT_LevelMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 引用已丢失.
        /// </summary>
        public static string CM_MissingReference {
            get {
                return ResourceManager.GetString("CM_MissingReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建关卡失败，详情：{0}.
        /// </summary>
        public static string ERR_CreateLevelFailure {
            get {
                return ResourceManager.GetString("ERR_CreateLevelFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关卡&apos;{0}&apos;已存在，请换一个名称。.
        /// </summary>
        public static string ERR_DuplicatedLevelName {
            get {
                return ResourceManager.GetString("ERR_DuplicatedLevelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件必须在工作区目录&apos;{0}&apos;内。.
        /// </summary>
        public static string ERR_FileInsideWorkspace {
            get {
                return ResourceManager.GetString("ERR_FileInsideWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载OpenGL Desktop失败，确保其版本为3.3及以上。.
        /// </summary>
        public static string ERR_GLContextFailure {
            get {
                return ResourceManager.GetString("ERR_GLContextFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;不是一个有效的工作区，或者由于某些原因损坏了。.
        /// </summary>
        public static string ERR_Invalid_Workspace {
            get {
                return ResourceManager.GetString("ERR_Invalid_Workspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 属性&apos;{0}&apos;的值不合法。.
        /// </summary>
        public static string ERR_InvalidFieldValue {
            get {
                return ResourceManager.GetString("ERR_InvalidFieldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关卡&apos;{0}&apos;不存在或者已损坏，无法加载。.
        /// </summary>
        public static string ERR_InvalidLevel {
            get {
                return ResourceManager.GetString("ERR_InvalidLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无效的关卡名，只能由字母、数字或下划线构成，且首字符不能为数字。.
        /// </summary>
        public static string ERR_InvalidLevelName {
            get {
                return ResourceManager.GetString("ERR_InvalidLevelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关卡&apos;{0}&apos;的元数据可能已经损坏，无法加载，详情：{1}.
        /// </summary>
        public static string ERR_LevelMetaCorrupt {
            get {
                return ResourceManager.GetString("ERR_LevelMetaCorrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;不存在。.
        /// </summary>
        public static string ERR_NonExist_Workspace {
            get {
                return ResourceManager.GetString("ERR_NonExist_Workspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile贴图切分尺寸不能为非正数。.
        /// </summary>
        public static string ERR_TileSplitMustBePositive {
            get {
                return ResourceManager.GetString("ERR_TileSplitMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile贴图切分尺寸大小不能超过256。.
        /// </summary>
        public static string ERR_TileSplitTooLarge {
            get {
                return ResourceManager.GetString("ERR_TileSplitTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建关卡.
        /// </summary>
        public static string H_CreateLevel {
            get {
                return ResourceManager.GetString("H_CreateLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前工作区.
        /// </summary>
        public static string H_CurrentWorkspace {
            get {
                return ResourceManager.GetString("H_CurrentWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 层级.
        /// </summary>
        public static string H_Layers {
            get {
                return ResourceManager.GetString("H_Layers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日志.
        /// </summary>
        public static string H_Log {
            get {
                return ResourceManager.GetString("H_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 实体属性.
        /// </summary>
        public static string H_ModifyEntities {
            get {
                return ResourceManager.GetString("H_ModifyEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 实体.
        /// </summary>
        public static string H_Placements {
            get {
                return ResourceManager.GetString("H_Placements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 属性.
        /// </summary>
        public static string H_Properties {
            get {
                return ResourceManager.GetString("H_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑.
        /// </summary>
        public static string MI_Edit {
            get {
                return ResourceManager.GetString("MI_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 复制.
        /// </summary>
        public static string MI_Edit_Copy {
            get {
                return ResourceManager.GetString("MI_Edit_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 剪切.
        /// </summary>
        public static string MI_Edit_Cut {
            get {
                return ResourceManager.GetString("MI_Edit_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 粘贴.
        /// </summary>
        public static string MI_Edit_Paste {
            get {
                return ResourceManager.GetString("MI_Edit_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重做.
        /// </summary>
        public static string MI_Edit_Redo {
            get {
                return ResourceManager.GetString("MI_Edit_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 撤销.
        /// </summary>
        public static string MI_Edit_Undo {
            get {
                return ResourceManager.GetString("MI_Edit_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件.
        /// </summary>
        public static string MI_File {
            get {
                return ResourceManager.GetString("MI_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭工作区.
        /// </summary>
        public static string MI_File_CloseWorkspace {
            get {
                return ResourceManager.GetString("MI_File_CloseWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出.
        /// </summary>
        public static string MI_File_Exit {
            get {
                return ResourceManager.GetString("MI_File_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新建工作区.
        /// </summary>
        public static string MI_File_NewWorkspace {
            get {
                return ResourceManager.GetString("MI_File_NewWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开最近....
        /// </summary>
        public static string MI_File_OpenRecent {
            get {
                return ResourceManager.GetString("MI_File_OpenRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开工作区.
        /// </summary>
        public static string MI_File_OpenWorkspace {
            get {
                return ResourceManager.GetString("MI_File_OpenWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存工作区.
        /// </summary>
        public static string MI_File_SaveWorkspace {
            get {
                return ResourceManager.GetString("MI_File_SaveWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工作区已保存。.
        /// </summary>
        public static string MSG_WorkspaceSaved {
            get {
                return ResourceManager.GetString("MSG_WorkspaceSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 复制(快捷键: Ctrl + C).
        /// </summary>
        public static string TT_CopyEntities {
            get {
                return ResourceManager.GetString("TT_CopyEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无变换(快捷键: Q).
        /// </summary>
        public static string TT_CursorMode {
            get {
                return ResourceManager.GetString("TT_CursorMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 剪切(快捷键: Ctrl + X).
        /// </summary>
        public static string TT_CutEntities {
            get {
                return ResourceManager.GetString("TT_CutEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 粘贴(快捷键: Ctrl + V).
        /// </summary>
        public static string TT_PasteEntities {
            get {
                return ResourceManager.GetString("TT_PasteEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 实体放置模式(快捷键: 2).
        /// </summary>
        public static string TT_PlaceMode {
            get {
                return ResourceManager.GetString("TT_PlaceMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 旋转(快捷键: E).
        /// </summary>
        public static string TT_RotateMode {
            get {
                return ResourceManager.GetString("TT_RotateMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 缩放(快捷键: R).
        /// </summary>
        public static string TT_ScaleMode {
            get {
                return ResourceManager.GetString("TT_ScaleMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 实体选中模式(快捷键: 1).
        /// </summary>
        public static string TT_SelectMode {
            get {
                return ResourceManager.GetString("TT_SelectMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 平移(快捷键: W).
        /// </summary>
        public static string TT_TranslateMode {
            get {
                return ResourceManager.GetString("TT_TranslateMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你确定要删除关卡&apos;{0}&apos;吗？此操作不可逆，请慎重选择！.
        /// </summary>
        public static string WARN_ConfirmDeleteLevel {
            get {
                return ResourceManager.GetString("WARN_ConfirmDeleteLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检测到当前工作区有未保存的修改，你是否要先保存再继续？.
        /// </summary>
        public static string WARN_ConfirmSaveWorkspace {
            get {
                return ResourceManager.GetString("WARN_ConfirmSaveWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检测到当前工作区有未保存的修改，是否要先保存再退出？.
        /// </summary>
        public static string WARN_ConfirmSaveWorkspaceExit {
            get {
                return ResourceManager.GetString("WARN_ConfirmSaveWorkspaceExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检测到当前工作区有未保存的修改，是否要先保存再切换关卡？.
        /// </summary>
        public static string WARN_ConfirmSaveWorkspaceSwitch {
            get {
                return ResourceManager.GetString("WARN_ConfirmSaveWorkspaceSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 节点数无法被删除至最小值以下。.
        /// </summary>
        public static string Warn_DeleteNodesFailed {
            get {
                return ResourceManager.GetString("Warn_DeleteNodesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 词条&apos;{0}&apos;未翻译！.
        /// </summary>
        public static string WARN_LocalizationNotFound {
            get {
                return ResourceManager.GetString("WARN_LocalizationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工作区&apos;{0}&apos;已经存在，你确定要继续吗？所有旧数据都会被清除。.
        /// </summary>
        public static string WARN_Replace_Exist_Workspace {
            get {
                return ResourceManager.GetString("WARN_Replace_Exist_Workspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入过滤文本....
        /// </summary>
        public static string WM_Filter {
            get {
                return ResourceManager.GetString("WM_Filter", resourceCulture);
            }
        }
    }
}
